api_doc:
    resource: "@DunglasJsonLdApiBundle/Resources/config/routing.xml"

api:
    resource: "."
    type:     "json-ld"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc
